### ISSUE TITLE
Does not work with Ajax?

### ISSUE THREAD

**Issue by beneklisefski** [BarrelStrength/Craft-EncodeEmail#3]
I'm trying to implement this script with ajax transition between my Craft pages. I think because the timing of when the email encoding function runs (too early) it's replacing my ajax content with just the email link generated by this plugin. I need to be able to time to trigger of this function so that is comes after the ajax process is over and doesn't disrupt the loading of content. Is this possible?

**Comment by BenParizek** [comment]
@beneklisefski Are any Twig filters working for you in your ajax requests?  Can you confirm everything works as expected when you are not using ajax?   And, could you post a code example of how you have things setup?

**Comment by beneklisefski** [comment]
@BenParizek All other Craft and Twig tags working fine. The email encoding worked fine before I implemented the AJAX. I have the site set up very similar to these instructions: https://designbycosmic.com/journal/craft-cms-ajax-page-transitions-with-history-pushstate

Right now I've reverted to using the entities option for encoding because it doesn't mess with the AJAX but would like to switch back to using stronger encoding if I can get it to work.

**Comment by BenParizek** [comment]
@beneklisefski I've added this to our ticket system.  I'll reach out again once we have a chance to look into it more.  I don't believe we're doing anything different with timing between any of the filters.  The biggest difference the rot13 encoding as opposed to the others is that it includes a <script> tag and that makes it a bit tricker to implement in some contexts.

**Comment by BenParizek** [comment]
@beneklisefski This issue should be fixed in the latest version: http://sprout.barrelstrengthdesign.com/craft-plugins/encode-email/updates#release-v1.2.1

**Comment by beneklisefski** [comment]
Thanks @BenParizek. One thing you may want to consider is changing from using a DIV to a SPAN for the container. I found injecting that block level element broke the styling I was using and it works less intrusively when changed to an inline span.

If anyone else needs to do this it's a simple change on line 77 of SproutEncodeEmailTwigExtension.php.

**Comment by BenParizek** [comment]
@beneklisefski: We released an update to Encode Email this week that fixes this div issue and replaces it with a span: http://sprout.barrelstrengthdesign.com/craft-plugins/encode-email/updates#release-v1.2.2
